sudo: true
language: node_js
node_js:
  - "10"
script:
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    monscript: ./install-up.sh && npm run deploy:production && up prune --retain=5
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./install-up.sh && npm run deploy:staging && up prune --retain=5
    on:
      branch: staging
