sudo: true
language: node_js
node_js:
  - "10"
script:
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: ./install-up.sh && npm run deploy:production
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./install-up.sh && npm run deploy:staging
    on:
      branch: staging
