version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14-browsers

git_restore_cache: &git_restore_cache
  restore_cache:
    keys:
      - source-v1-{{ .Branch }}-{{ .Revision }}
      - source-v1-{{ .Branch }}-
      - source-v1-

git_save_cache: &git_save_cache
  save_cache:
    key: source-v1-{{ .Branch }}-{{ .Revision }}
    paths:
      - ".git"


prep_deploy: &prep_deploy
  run:
    name: Prep deploy
    command: |
      # apt-get python stuff?
      #sudo apt-get install python3-pip python3-dev build-essential
      # Install pip
      #curl https://bootstrap.pypa.io/pip/3.5/get-pip.py -o get-pip.py
      #sudo python3 get-pip.py
      # awscli dependencies
      # sudo apt-get install python-dev
      # Install awscli
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

jobs:
  install_and_build:
    <<: *defaults
    steps:
      - *git_restore_cache
      - checkout
      - *git_save_cache
      - run:
          name: npm install
          command: npm ci --only=prod
      - run:
          name: Build
          command: NODE_ENV=production npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
            - public
  deploy_production:
    <<: *defaults
    steps:
      - *git_restore_cache
      - checkout
      - *git_save_cache
      - attach_workspace:
          at: ~/repo
      - *prep_deploy
      - run:
          name: Deploy to S3
          command: npm run deploy:production

workflows:
  version: 2
  install_and_test_and_deploy:
    jobs:
      - install_and_build
      - deploy_production:
          context: apex-up
          requires:
            - install_and_build
          filters:
            branches:
              only: master
  install_and_test_and_deploy2:
    jobs:
      - install_and_build
      - deploy_production:
          context: apex-up
          requires:
            - install_and_build
          filters:
            branches:
              only: master
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
